name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    environment: secrets

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24.4

      - name: Run tests
        run: go test -v -cover ./...

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/kvstore-api:latest .
          docker push ghcr.io/${{ github.repository_owner }}/kvstore-api:latest

  deploy:
    needs: build-test-push
    runs-on: ubuntu-latest
    environment: secrets

    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            cd ${{ secrets.PATH }}
            git pull origin main
            echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker pull ghcr.io/${{ github.repository_owner }}/kvstore-api:latest
            docker compose -f ${{ secrets.PATH }}/docker-compose.prod.yml up -d

